config/routes.rb
Rails.application.routes.draw do
  #get 'home/zipcode'
  root 'home#index'

  post "zipcode" => 'home#zipcode'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	require 'net/http'
  	require 'json'
  	@url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=89129&distance=0&API_KEY=191290CA-9661-48F1-8A0C-17B9FBEFB4B8'
  	#@url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=12345&distance=0&API_KEY=191290CA-9661-48F1-8A0C-17B9FBEFB4B8'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@output = JSON.parse(@response)

  	if @output.empty?
  		@final_output = "Error"
  	elsif !@output
  		@final_output = "Error"
  	else
  		@final_output = @output[0]['AQI']
  	end

  	if @final_output == "Error"
  		@api_color = "gray"
  		@api_description = "Unable to find the air quality"
  	elsif @final_output <= 50
  		@api_color = "green"
  		@api_description = "Air quality is very good"
  	elsif @final_ouptut >= 51 && @final_output <= 100
  		@api_color ="yellow"
  		@api_description = "Air quality is OK"
	else
  		@api_color ="yellow"
  		@api_description = "Air quality is not bad"
  	end
  end

  def zipcode
  	@zip_query = params[:zipcode]
  	if params[:zipcode] == ""
  		@zip_query = "Hey you forget to put something"
  	elsif params[:zipcode]
  		require 'net/http'
	  	require 'json'
	  	@url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode='+ @zip_query.to_s + '&distance=0&API_KEY=191290CA-9661-48F1-8A0C-17B9FBEFB4B8'
	  	#@url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=12345&distance=0&API_KEY=191290CA-9661-48F1-8A0C-17B9FBEFB4B8'
	  	@uri = URI(@url)
	  	@response = Net::HTTP.get(@uri)
	  	@output = JSON.parse(@response)

	  	if @output.empty?
	  		@final_output = "Error"
	  	elsif !@output
	  		@final_output = "Error"
	  	else
	  		@final_output = @output[0]['AQI']
	  	end

	  	if @final_output == "Error"
	  		@api_color = "gray"
	  		@api_description = "Unable to find the air quality"
	  	elsif @final_output <= 50
	  		@api_color = "green"
	  		@api_description = "Air quality is very good"
	  	elsif @final_output >= 51 && @final_output <= 100
	  		@api_color ="yellow"
	  		@api_description = "Air quality is OK"
		else
	  		@api_color ="yellow"
	  		@api_description = "Air quality is not bad"
	  	end
  	end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "My Ozone", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        
      </li>
    </ul>
      <%= form_tag zipcode_path, :method => 'POST' do %>
      <div class="form-inline my-2 my-lg-0">
        <%= text_field_tag 'zipcode' , nil, placeholder: "Search zipcode", class: "form-control mr-sm-2" %>
        <%= submit_tag 'Search', class: 'btn btn-outline-secondary my-2 my-sm-0' %>
      <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout for my neighbourhood </p>
  <hr class="my-4">
  <p> <%= @api_description %></p>
  
</div>

<br/>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout for my neighbourhood </p>
  <hr class="my-4">
  <p> <%= @api_description %></p>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
  </body>
</html>